server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9183
  servlet:
    context-path: /
spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # MYSQL 5 \u9A71\u52A8\uFF1Acom.mysql.jdbc.Driver\uFF0CMYSQL 6+ \u9A71\u52A8\uFF1Acom.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.24.184:3306/doudou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 205d0dd90c46
    # \u8FDE\u63A5\u6C60\u914D\u7F6E
    druid:
      # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
      initial-size: 5
      min-idle: 5
      max-active: 20
      # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      max-wait: 60000
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u6BEB\u79D2
      time-between-eviction-runs-millis: 60000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # \u6253\u5F00 PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0A PSCache \u7684\u5927\u5C0F
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684 Filter\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762 SQL \u65E0\u6CD5\u7EDF\u8BA1\uFF0Cwall \u7528\u4E8E\u9632\u706B\u5899
      filters: stat,wall,log4j2
      # \u901A\u8FC7 connection-properties \u5C5E\u6027\u6253\u5F00 mergeSql \u529F\u80FD\uFF1B\u6162 SQL \u8BB0\u5F55
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # \u914D\u7F6E DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # \u914D\u7F6E DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP \u767D\u540D\u5355\uFF0C\u6CA1\u6709\u914D\u7F6E\u6216\u8005\u4E3A\u7A7A\uFF0C\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE
        allow: 127.0.0.1
        # IP \u9ED1\u540D\u5355\uFF0C\u82E5\u767D\u540D\u5355\u4E5F\u5B58\u5728\uFF0C\u5219\u4F18\u5148\u4F7F\u7528
        deny: 192.168.31.253
        # \u7981\u7528 HTML \u4E2D Reset All \u6309\u94AE
        reset-enable: false
        # \u767B\u5F55\u7528\u6237\u540D/\u5BC6\u7801
        login-username: root
        login-password: 123
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: YYIQXFPANXFGYUFE
    port: 25
    protocol: smtp
    username: Insalonhair@163.com

logging:
  config: classpath:log4j2.xml
mybatis-plus:
  # \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # \u5982\u679C\u662F\u653E\u5728resource\u76EE\u5F55 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/**/*.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: cn.saytime.model
  global-config:
    #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
    id-type: 0
    #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
    field-strategy: 1
  #\u539F\u751F\u914D\u7F6E
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
